### ISSUE TITLE
Mood2SpotifyRec Project

### ISSUE THREAD

**Issue by menamerai** [polskiXO/python-beginner-projects#1]
Tasklist:

- [x] #27
- [x] #21
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #28

**Comment by menamerai** [comment]
![Mood2Spotify](https://github.com/polskiXO/python-beginner-projects/assets/62800649/4fbb8e2c-0d0a-4e77-aa7a-27503d4b5138)

**Comment by polskiTran** [comment]
@menamerai https://developer.spotify.com/documentation/web-api/reference/get-audio-features

**Comment by menamerai** [comment]
Looks like `valence` is our main guy, but we could also focus on `energy`, `instrumentalness`, `,loudness`, `tempo`, and maybe other metrics too.

**Comment by menamerai** [comment]
@polskiXO made a branch for this project (`1-mood2spotifyrec-project`). We should work from this branch and make a PR when we're done.
