### ISSUE TITLE
Spotify API stats analysis (analyze what stats there are and how we could use it for our mood matching)

### ISSUE THREAD

**Issue by menamerai** [polskiXO/python-beginner-projects#21]
Comment your findings here in this issue.

**Comment by polskiTran** [comment]
@menamerai 
- [spotify track audio's feature](https://developer.spotify.com/documentation/web-api/reference/get-audio-features)
- [additional track audio's analysi](https://developer.spotify.com/documentation/web-api/reference/get-audio-analysis)
