### ISSUE TITLE
Set up streamlit frontend

### ISSUE THREAD

**Issue by menamerai** [polskiXO/python-beginner-projects#9]
Use `streamlit` to set up a frontend that has a text input, and location for the LLM to return its answer to.

Remember to run `poetry run streamlit run app.py` to run your server, since poetry takes care of the dependency. Or you can run `poetry shell` and then `streamlit run app.py`

**Comment by polskiTran** [comment]
PR Pushed https://github.com/polskiXO/python-beginner-projects/pull/14
